name: Test and Deploy

on: [push]

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9"]
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v3
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m venv .venv
                . .venv/bin/activate
                pip install --upgrade pip
                pip install poetry
                poetry install
            - name: Run tests
              run: |
                . .venv/bin/activate
                pytest

    deploy:
        needs: tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9"]
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v3
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                sudo apt update
                sudo apt install awscli -y

                python -m venv .venv
                . .venv/bin/activate
                pip install --upgrade pip
                pip install poetry
                poetry export --without-hashes -o requirements.txt
                pip install -r requirements.txt --target packages
            - name: Build
              run: |
                cd packages
                zip -r9 ../lambda_package.zip .
                cd ..
                zip -gr9 lambda_package.zip service
                zip -g9 lambda_package.zip lambda_function.py
                zip -g9 lambda_package.zip logging.conf
            - name: Deploy
              run: |
                aws lambda update-function-code \
                    --function-name calculadora-de-dano \
                    --zip-file fileb://lambda_package.zip

    post_deploy:
        needs: deploy
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9"]
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v3
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m venv .venv
                . .venv/bin/activate
                pip install --upgrade pip
                pip install poetry
                poetry install
            - name: Run tests
              run: |
                . .venv/bin/activate
                pytest end2end-test.py
